/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HomeLogin;

import court.Court;
import help.Help;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Hospital.Hospital;
import disciplinary.Disciplinary;
import prisoner.Prisoner;
import visitors.Visitors;

/**
 *
 * @author Owe
 */
public class HomeLogin extends javax.swing.JFrame {
    
    //integer tio count the number of attempts per the system
    int attempts = 0;

    /**
     * Creates new form Login
     */
    public HomeLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jtxtUserName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jpassword = new javax.swing.JPasswordField();
        jtbnCancel = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnLogin2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtnHospital = new javax.swing.JButton();
        jtbnPrisoner = new javax.swing.JButton();
        jtbnCourt = new javax.swing.JButton();
        jtbnOfficers = new javax.swing.JButton();
        jbtnVisitors = new javax.swing.JButton();
        jtbnDisciplinary = new javax.swing.JButton();
        jtbnHelp = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("User Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 140, 50));

        jtxtUserName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtUserName.setText("Admin");
        jtxtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUserNameActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 200, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, 30));

        jpassword.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 230, 40));

        jtbnCancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtbnCancel.setText("Cancel");
        jtbnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jtbnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 140, 50));

        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 140, 50));

        jbtnLogin2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnLogin2.setText("Login");
        jbtnLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLogin2ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 140, 50));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Admin Login System");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 510, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 594, 369));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("KENYA PRISON  MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 48, 1040, -1));

        jbtnHospital.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnHospital.setText("Hospital");
        jbtnHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHospitalActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jtbnPrisoner.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtbnPrisoner.setText("Prisoner");
        jtbnPrisoner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnPrisonerActionPerformed(evt);
            }
        });
        getContentPane().add(jtbnPrisoner, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jtbnCourt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtbnCourt.setText("Court");
        jtbnCourt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnCourtActionPerformed(evt);
            }
        });
        getContentPane().add(jtbnCourt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 130, -1));

        jtbnOfficers.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtbnOfficers.setText("Officers");
        jtbnOfficers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnOfficersActionPerformed(evt);
            }
        });
        getContentPane().add(jtbnOfficers, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        jbtnVisitors.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnVisitors.setText("Visitors");
        jbtnVisitors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVisitorsActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnVisitors, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 290, 170, -1));

        jtbnDisciplinary.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtbnDisciplinary.setText("Disciplinary");
        jtbnDisciplinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnDisciplinaryActionPerformed(evt);
            }
        });
        getContentPane().add(jtbnDisciplinary, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 200, -1, -1));

        jtbnHelp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtbnHelp.setText("Help");
        jtbnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnHelpActionPerformed(evt);
            }
        });
        getContentPane().add(jtbnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 397, 140, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUserNameActionPerformed

    private void jtbnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnCancelActionPerformed
        // clear data inside the fields for both Password and User Name
        jtxtUserName.setText("");
        jpassword.setText("");
    }//GEN-LAST:event_jtbnCancelActionPerformed

    private void jbtnHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHospitalActionPerformed
        //Call the Hospital pages here 
        Hospital theHospital = new Hospital();
        theHospital.setVisible(true);
    }//GEN-LAST:event_jbtnHospitalActionPerformed

    private void jtbnPrisonerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnPrisonerActionPerformed
        // Open page fo the Prison
        Prisoner iPrisoner = new Prisoner();
        iPrisoner.setVisible(true);
    }//GEN-LAST:event_jtbnPrisonerActionPerformed

    private void jtbnCourtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnCourtActionPerformed
        // Cour Page Intent
        Court iCourt = new Court();
        iCourt.setVisible(true);
    }//GEN-LAST:event_jtbnCourtActionPerformed

    private void jtbnOfficersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnOfficersActionPerformed
        // the court Page
        Court icourt = new Court();
        icourt.setVisible(true);
    }//GEN-LAST:event_jtbnOfficersActionPerformed

    private void jbtnVisitorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVisitorsActionPerformed
        // Visitors Page
        Visitors iVisitors = new Visitors();
        iVisitors.setVisible(true);
    }//GEN-LAST:event_jbtnVisitorsActionPerformed

    private void jtbnDisciplinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnDisciplinaryActionPerformed
        // Discciplinary Page
        Disciplinary iDisciplinary = new Disciplinary();
        iDisciplinary.setVisible(true);
    }//GEN-LAST:event_jtbnDisciplinaryActionPerformed

    private void jtbnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnHelpActionPerformed
        // TODO add your handling code here:
        Help iHelp = new Help();
        iHelp.setVisible(true);
    }//GEN-LAST:event_jtbnHelpActionPerformed

    private void jbtnLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLogin2ActionPerformed
        // check admin privilages if they are right
        String UserName = jtxtUserName.getText();
        String UserPassword = jpassword.getText();
        if(UserName.contains("Admin") && (UserPassword.contains("123")))
        {
            //activate the rest of the buttons
            jtxtUserName.setText("");
            jpassword.setText("");
            
        jtbnDisciplinary.setEnabled(true);
        jtbnPrisoner.setEnabled(true);
        jbtnHospital.setEnabled(true);
        jtbnCourt.setEnabled(true);
        jtbnOfficers.setEnabled(true);
        jtbnDisciplinary.setEnabled(true);
        jbtnVisitors.setEnabled(true);
        jtbnHelp.setEnabled(true);
            
        }
        else if (!(UserName.contains("Admin") && (UserPassword.contains("123"))))
        {
            //do not activate the buttons
        jtbnDisciplinary.setEnabled(false);
        jtbnPrisoner.setEnabled(false);
        jbtnHospital.setEnabled(false);
        jtbnCourt.setEnabled(false);
        jtbnOfficers.setEnabled(false);
        jtbnDisciplinary.setEnabled(false);
        jbtnVisitors.setEnabled(false);
        jtbnHelp.setEnabled(false);
        
        attempts += 1;
        
        if(attempts == 3)
        {
            System.exit(0);
        }
        }
        
    }//GEN-LAST:event_jbtnLogin2ActionPerformed
//declare a private variable
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // confirm exit of the system by the user
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm Exit", 
                "Prison ManageMent System",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION);
        //TODO work on the Wrong password Enter to exit;
        {
               System.exit(0); // Automatic exit if more than 3 wrong trials
        }
            
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //Deactivate if the user has failed to login
        jtbnDisciplinary.setEnabled(false);
        jtbnPrisoner.setEnabled(false);
        jbtnHospital.setEnabled(false);
        jtbnCourt.setEnabled(false);
        jtbnOfficers.setEnabled(false);
        jtbnDisciplinary.setEnabled(false);
        jbtnVisitors.setEnabled(false);
        jtbnHelp.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void jpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnHospital;
    private javax.swing.JButton jbtnLogin2;
    private javax.swing.JButton jbtnVisitors;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JButton jtbnCancel;
    private javax.swing.JButton jtbnCourt;
    private javax.swing.JButton jtbnDisciplinary;
    private javax.swing.JButton jtbnHelp;
    private javax.swing.JButton jtbnOfficers;
    private javax.swing.JButton jtbnPrisoner;
    private javax.swing.JTextField jtxtUserName;
    // End of variables declaration//GEN-END:variables
}
