/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package court;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import HomeLogin.HomeLogin;
import disciplinary.Disciplinary;

/**
 *
 * @author Owe
 */
public class Court extends javax.swing.JFrame {

    /**
     * Creates new form Court
     */
    public Court() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jStation = new javax.swing.JLabel();
        jFinalCourtDescition = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateCase = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPenality = new javax.swing.JTextField();
        jhealthCause = new javax.swing.JLabel();
        jFine = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jpunishment = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jOfficerInCharge = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jJudgeContact = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jNextCaseDate = new javax.swing.JTextField();
        jCmbID = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jlogout = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jStation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jStation.setText("Final Desicion");
        getContentPane().add(jStation, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 30));

        jFinalCourtDescition.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFinalCourtDescition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFinalCourtDescitionActionPerformed(evt);
            }
        });
        getContentPane().add(jFinalCourtDescition, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 170, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Court Ref");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Date of Case");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        jDateCase.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jDateCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateCaseActionPerformed(evt);
            }
        });
        getContentPane().add(jDateCase, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 170, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Penalities");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 30));

        jPenality.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPenality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPenalityActionPerformed(evt);
            }
        });
        getContentPane().add(jPenality, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 170, 30));

        jhealthCause.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jhealthCause.setText("Fine (Ksh)");
        getContentPane().add(jhealthCause, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, 30));

        jFine.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jFine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFineActionPerformed(evt);
            }
        });
        getContentPane().add(jFine, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 170, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Punishment");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 120, 30));

        jpunishment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jpunishment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpunishmentActionPerformed(evt);
            }
        });
        getContentPane().add(jpunishment, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 50, 160, 40));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Officers in charge");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, 30));

        jOfficerInCharge.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jOfficerInCharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOfficerInChargeActionPerformed(evt);
            }
        });
        getContentPane().add(jOfficerInCharge, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 110, 160, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Judge's Contact");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, 30));

        jJudgeContact.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jJudgeContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jJudgeContactActionPerformed(evt);
            }
        });
        getContentPane().add(jJudgeContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 160, 40));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("Next Date");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 130, 30));

        jNextCaseDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jNextCaseDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextCaseDateActionPerformed(evt);
            }
        });
        getContentPane().add(jNextCaseDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 160, 40));

        jCmbID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCmbID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Victim's Name", "Kelvin", "Mwangi", "Owen", "Njoroge", "William" }));
        jCmbID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbIDActionPerformed(evt);
            }
        });
        getContentPane().add(jCmbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 43, 170, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Victim Name", "Court Decision", "Date of Case", "Penalties", "Fine (KSH)", "Punishment", "Officer in charge", "Judge Contact", "Next Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 910, 180));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 130, 30));

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 130, 30));

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        jButton4.setText("Disciplinary");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 130, 30));

        jlogout.setText("LogOut");
        jlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlogoutActionPerformed(evt);
            }
        });
        jPanel1.add(jlogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 130, 30));

        jButton6.setText("Home");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 890, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFinalCourtDescitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFinalCourtDescitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFinalCourtDescitionActionPerformed

    private void jDateCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateCaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateCaseActionPerformed

    private void jPenalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPenalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPenalityActionPerformed

    private void jFineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFineActionPerformed

    private void jpunishmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpunishmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpunishmentActionPerformed

    private void jOfficerInChargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOfficerInChargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOfficerInChargeActionPerformed

    private void jJudgeContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jJudgeContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jJudgeContactActionPerformed

    private void jNextCaseDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextCaseDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNextCaseDateActionPerformed

    private void jCmbIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbIDActionPerformed
        // Make the button auto fill the deatils of the individuals
        if(jCmbID.getSelectedItem().equals("Owen"))
        {
            //perform the task here
            jFinalCourtDescition.setText("Muder");
            jDateCase.setText("22/06/2015");
            jPenality.setText("No access to computer");
            jFine.setText("20,000");
            jpunishment.setText("Kitchen Cleaning");
            jOfficerInCharge.setText("Captain Kemeja");
            jJudgeContact.setText("07403541678");
            jNextCaseDate.setText("22/12/2016");
        }
        else if (jCmbID.getSelectedItem().equals("Mwangi"))
        {
            //Perform System Closure to doctor in charge;
            jFinalCourtDescition.setText("No Evidence");
            jDateCase.setText("22/2/2012");
            jPenality.setText("No penalty");
            jFine.setText("0.00");
            jpunishment.setText("None");
            jOfficerInCharge.setText("Captain Simuyu");
            jJudgeContact.setText("07768213567");
            jNextCaseDate.setText("N/A");
        }
        else if (jCmbID.getSelectedItem().equals("Kelvin"))
        {
            jFinalCourtDescition.setText("impresonment");
            jDateCase.setText("11/1/2018");
            jPenality.setText("Tree weeding");
            jFine.setText("2,000");
            jpunishment.setText("1 month imprisonment");
            jOfficerInCharge.setText("Captain Kalya");
            jJudgeContact.setText("07404012456");
            jNextCaseDate.setText("5/06/2019");
        }
          else if (jCmbID.getSelectedItem().equals("Njoroge"))
        {
            jFinalCourtDescition.setText("Released");
            jDateCase.setText("22/8/2020");
            jPenality.setText("N/A");
            jFine.setText("0.00");
            jpunishment.setText("N/A");
            jOfficerInCharge.setText("Captain Katui");
            jJudgeContact.setText("07101010102");
            jNextCaseDate.setText("N/A");
        }
          else if (jCmbID.getSelectedItem().equals("William"))
        {
            jFinalCourtDescition.setText("Imprisonment");
            jDateCase.setText("25/12/2018");
            jPenality.setText("Street Cleaness");
            jFine.setText("450,000");
            jpunishment.setText("3 strokes daily");
            jOfficerInCharge.setText("Captain Sawa");
            jJudgeContact.setText("0775456938");
            jNextCaseDate.setText("22/12/2020");
        }
             else if (jCmbID.getSelectedItem().equals("Victim's Name"))
        {
            jFinalCourtDescition.setText("");
            jDateCase.setText("");
            jPenality.setText(" ");
            jFine.setText("");
            jpunishment.setText("  ");
            jOfficerInCharge.setText(" ");
            jJudgeContact.setText("");
            jNextCaseDate.setText("");
        }
        else
                {
                    //make sure to entwe data
                }

    }//GEN-LAST:event_jCmbIDActionPerformed

    private JFrame frame;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //delete added data to the table
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm Exit",
            "Prison ManageMent System",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION);
    //TODO work on the Wrong password Enter to exit;
    {
        System.exit(0); // Automatic exit if more than 3 wrong trials
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //delete added data
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        if(jTable1.getSelectedRow()==-1)
        {
            if(jTable1.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(null,"No data to Delete",
                    "Prison Management System", JOptionPane.OK_OPTION);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Select Row To delete", "Prison Management System",
                    JOptionPane.OK_OPTION);
            }
        }
        else
        {
            tableModel.removeRow(jTable1.getSelectedRow());
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Table update data
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();

        //update data to the table
        tableModel.addRow(new Object[]{
            jCmbID.getSelectedItem().toString(),
            jDateCase.getText(),
            jPenality.getText(),
            jFine.getText(),
            jpunishment.getText(),
            jOfficerInCharge.getText(),
            jJudgeContact.getText(),
            jNextCaseDate.getText(),
        });

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlogoutActionPerformed
        // logout t'he user from the system by retrning the user to the login page
        HomeLogin iLogin = new HomeLogin();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jlogoutActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //Court Home Page
       HomeLogin iLogin = new HomeLogin();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         Disciplinary iDisciplinary = new Disciplinary();
         iDisciplinary.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Court.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Court.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Court.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Court.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Court().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jCmbID;
    private javax.swing.JTextField jDateCase;
    private javax.swing.JTextField jFinalCourtDescition;
    private javax.swing.JTextField jFine;
    private javax.swing.JTextField jJudgeContact;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jNextCaseDate;
    private javax.swing.JTextField jOfficerInCharge;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jPenality;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jStation;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jhealthCause;
    private javax.swing.JButton jlogout;
    private javax.swing.JTextField jpunishment;
    // End of variables declaration//GEN-END:variables
}
